### ISSUE TITLE
HHVM errors with PharException

### ISSUE THREAD

**Issue by padraic** [humbug/phar-updater#29]
Appears on Travis and looks like:
```
2) Humbug\Test\SelfUpdate\UpdaterTest::testUpdatePhar
PharException: phar has a broken or unsupported signature

/home/padraic/projects/phar-updater/src/Updater.php:470
/home/padraic/projects/phar-updater/src/Updater.php:364
/home/padraic/projects/phar-updater/src/Updater.php:139
/home/padraic/projects/phar-updater/tests/Humbug/Test/SelfUpdate/UpdaterTest.php:145
```
From what I've been able to tell, this is probably a straight up incompatibility within HHVM, but figured I'd note it here anyway. It would likely then impact any openssl signed PHAR beyond this project. Someone else have other ideas, or has better familiarity with HHVM, so let me know.

**Comment by theofidry** [comment]
Unless someone is really up for officially supporting HHVM, I'm not really for supporting it, it can be a lot of extra work.

**Comment by padraic** [comment]
Closed as answered. We'll continue testing hhvm, but this does appear to a HHVM issue which we can't workaround. Will check if previously reported, and otherwise raise it there.
